service:
  type: ClusterIP

# persistence:
#   enabled: true
#   storageClassName: standard
#   size: 3Gi

adminUser: admin
adminPassword: ChangeMeStrong

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir-gateway.monitoring.svc.cluster.local:80/prometheus
        isDefault: true
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local:80
        editable: true